server:
  port: 8091

management:
  secrity:
    enabled: false

spring:
  freemarker:
    enabled: true
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    view:
      suffix: .html
      prefix: /WEB-INF/view
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  aop:
    proxy-target-class: true

    
