---

server:
  port: 8091

management:
  secrity:
    enabled: false

spring:
  freemarker:
    enabled: true
    suffix: .html
    template-loader-path: classpath:/WEB-INF/ftl/
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: /static/**
  aop:
    proxy-target-class: true
    
---

spring:
  profiles: dev    
  datasource:
    url: jdbc:mysql://127.0.0.1:12306/yyy?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: password
    filters: log4j,wall,mergeStat

